# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vtag',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/vtag',
                'lib_path': 'vtag'},
  'syms': {'vtag.core': {'vtag.core.foo': ('core.html#foo', 'vtag/core.py')}}}
